name: Publish to PyPI

on:
  # Se déclenche lors d'une release GitHub
  release:
    types: [published]

  # Se déclenche aussi sur les tags vX.Y.Z
  push:
    tags:
      - 'v*.*.*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine

    - name: Build package
      run: python -m build

    - name: Check package
      run: twine check dist/*

    - name: Publish to Test PyPI (si tag contient 'rc' ou 'beta')
      if: contains(github.ref, 'rc') || contains(github.ref, 'beta')
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_API_TOKEN }}
      run: |
        twine upload --repository testpypi dist/* --skip-existing

    - name: Publish to PyPI (si tag stable)
      if: "!contains(github.ref, 'rc') && !contains(github.ref, 'beta')"
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        twine upload dist/* --skip-existing
